name: Linux

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Installation
        run: |
          sudo apt-get install -y cmake
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
          sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-9 60
          sudo update-alternatives --set g++ /usr/bin/g++-9
          sudo update-alternatives --set gcc /usr/bin/gcc-9
          sudo update-alternatives --set cpp /usr/bin/cpp-9

      - name: Tests
        run: |
          cmake example
          make

