name: macOS

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Installation
        run: |
          brew install cmake

      - name: Tests
        run: |
          ./ci/test-unix.sh
